DROP TABLE IF EXISTS cryptoCurrency;
DROP TABLE IF EXISTS cryptoWallet;

CREATE TABLE cryptoCurrency ( 
  idCrypto INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
  name VARCHAR(50) NOT NULL DEFAULT 'N/D',
  symbol VARCHAR(6) NOT NULL,
  delta DECIMAL(30,9),
  currentPrice DECIMAL(30,9) NOT NULL,
  imageUrl VARCHAR(50),
  lastUpdated TIMESTAMP  NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY (idCrypto)
);

CREATE TABLE cryptoWallet (
    idWallet INTEGER not NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    idCrypto INTEGER NOT NULL,
    purchasePrice DECIMAL(30,9) not NULL,
    quantity DECIMAL(20,19) NOT NULL,
    purchaseDate TIMESTAMP  NOT NULL default CURRENT_TIMESTAMP,
    PRIMARY KEY (idWallet),
    FOREIGN KEY (idCrypto) REFERENCES cryptoCurrency (idCrypto)
);